name: CI/CD Pipeline

# Trigger on pushes to main (or PRs targeting main)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest app/tests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Image digest (for reference)
      run: echo "Image pushed:" ${{ secrets.DOCKER_USERNAME }}"/flask-app:latest"
